//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbHospitalRevisitEntities : DbContext
    {
        public dbHospitalRevisitEntities()
            : base("name=dbHospitalRevisitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbCaller_Question> tbCaller_Question { get; set; }
        public DbSet<tbCaller_Title> tbCaller_Title { get; set; }
        public DbSet<tbCirculation> tbCirculation { get; set; }
        public DbSet<tbContent_Record> tbContent_Record { get; set; }
        public DbSet<tbDeal_Way> tbDeal_Way { get; set; }
        public DbSet<tbDepartment> tbDepartment { get; set; }
        public DbSet<tbDiagnosis> tbDiagnosis { get; set; }
        public DbSet<tbInformation_Register> tbInformation_Register { get; set; }
        public DbSet<tbInvestigation_Key> tbInvestigation_Key { get; set; }
        public DbSet<tbInvestigation_Question> tbInvestigation_Question { get; set; }
        public DbSet<tbMessage_Sample> tbMessage_Sample { get; set; }
        public DbSet<tbMessage_Send_Plan> tbMessage_Send_Plan { get; set; }
        public DbSet<tbPatient> tbPatient { get; set; }
        public DbSet<tbPersonnal_Caller> tbPersonnal_Caller { get; set; }
        public DbSet<tbPhoneBook> tbPhoneBook { get; set; }
        public DbSet<tbPoint_Out> tbPoint_Out { get; set; }
        public DbSet<tbReference_Information> tbReference_Information { get; set; }
        public DbSet<tbReview_Project_Name> tbReview_Project_Name { get; set; }
        public DbSet<tbRole> tbRole { get; set; }
        public DbSet<tbStaff> tbStaff { get; set; }
        public DbSet<tbStaffDuty> tbStaffDuty { get; set; }
        public DbSet<tbVisits_Information> tbVisits_Information { get; set; }
        public DbSet<tbVoice_Key> tbVoice_Key { get; set; }
        public DbSet<tbVoice_Plan> tbVoice_Plan { get; set; }
    }
}
