//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaller_Title
    {
        public tbCaller_Title()
        {
            this.tbCaller_Question = new HashSet<tbCaller_Question>();
            this.tbVoice_Plan = new HashSet<tbVoice_Plan>();
            this.tbVoice_Key = new HashSet<tbVoice_Key>();
        }
    
        public int Caller_Title_ID { get; set; }
        public string Caller_Title_Name { get; set; }
    
        public virtual ICollection<tbCaller_Question> tbCaller_Question { get; set; }
        public virtual ICollection<tbVoice_Plan> tbVoice_Plan { get; set; }
        public virtual ICollection<tbVoice_Key> tbVoice_Key { get; set; }
    }
}
