//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaller_Question
    {
        public int Caller_Question_ID { get; set; }
        public Nullable<int> Caller_Title_ID { get; set; }
        public Nullable<int> Investigation_Question_ID { get; set; }
    
        public virtual tbCaller_Title tbCaller_Title { get; set; }
        public virtual tbInvestigation_Question tbInvestigation_Question { get; set; }
    }
}
