//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDeal_Way
    {
        public tbDeal_Way()
        {
            this.tbPoint_Out = new HashSet<tbPoint_Out>();
        }
    
        public int Deal_Way_ID { get; set; }
        public string Processing_Method { get; set; }
    
        public virtual ICollection<tbPoint_Out> tbPoint_Out { get; set; }
    }
}
