//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDiagnosis
    {
        public tbDiagnosis()
        {
            this.tbVoice_Plan = new HashSet<tbVoice_Plan>();
        }
    
        public int Diagnosis_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public string In_Hospital_NO { get; set; }
        public string Principal_Diagnosis { get; set; }
        public string Out_Hospital_Advice { get; set; }
        public string Department_ID { get; set; }
        public Nullable<System.DateTime> In_Hospital_Date { get; set; }
        public Nullable<System.DateTime> Out_Hospital_Date { get; set; }
        public Nullable<System.DateTime> Rediagnose_Date { get; set; }
        public string Rediagnose_Department_ID { get; set; }
        public string Rediagnose_Doctor { get; set; }
        public Nullable<bool> Is_Assign_Voice_Survey { get; set; }
        public Nullable<bool> Is_Assign_Manual_Survey { get; set; }
    
        public virtual ICollection<tbVoice_Plan> tbVoice_Plan { get; set; }
    }
}
