//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInvestigation_Question
    {
        public tbInvestigation_Question()
        {
            this.tbInvestigation_Key = new HashSet<tbInvestigation_Key>();
            this.tbVoice_Key = new HashSet<tbVoice_Key>();
        }
    
        public int Investigation_Question_ID { get; set; }
        public string Review_Content { get; set; }
        public string File_Paths { get; set; }
    
        public virtual tbCaller_Question tbCaller_Question { get; set; }
        public virtual ICollection<tbInvestigation_Key> tbInvestigation_Key { get; set; }
        public virtual ICollection<tbVoice_Key> tbVoice_Key { get; set; }
    }
}
