//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInformation_Register
    {
        public tbInformation_Register()
        {
            this.tbPoint_Out = new HashSet<tbPoint_Out>();
        }
    
        public int Information_Register_ID { get; set; }
        public Nullable<int> Personnal_Caller_ID { get; set; }
        public string Consulting_Phone_Number { get; set; }
        public Nullable<System.DateTime> Air_Time { get; set; }
        public string Involve_Content { get; set; }
        public Nullable<int> Involve_Department_ID { get; set; }
        public Nullable<int> Involve_StaffInfo_ID { get; set; }
        public string Involve_Content_Qualitative { get; set; }
        public Nullable<bool> Is_Moving { get; set; }
        public Nullable<int> SOSC_CSR_ID { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<tbPoint_Out> tbPoint_Out { get; set; }
    }
}
