//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMessage_Sample
    {
        public int Message_Sample_ID { get; set; }
        public string Message_Content { get; set; }
        public string MMS_Path { get; set; }
        public Nullable<int> Parent_ID { get; set; }
    
        public virtual tbMessage_Sample tbMessage_Sample1 { get; set; }
        public virtual tbMessage_Sample tbMessage_Sample2 { get; set; }
        public virtual tbMessage_Sample tbMessage_Sample11 { get; set; }
        public virtual tbMessage_Sample tbMessage_Sample3 { get; set; }
    }
}
