//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPatient
    {
        public tbPatient()
        {
            this.tbPhoneBook = new HashSet<tbPhoneBook>();
            this.tbVoice_Plan = new HashSet<tbVoice_Plan>();
        }
    
        public int Patient_ID { get; set; }
        public string Heath_Card { get; set; }
        public string Document_No { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Is_Dead { get; set; }
    
        public virtual ICollection<tbPhoneBook> tbPhoneBook { get; set; }
        public virtual ICollection<tbVoice_Plan> tbVoice_Plan { get; set; }
    }
}
