//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersonnal_Caller
    {
        public int Personnal_Caller_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Vioce_Key_Account_ID { get; set; }
        public Nullable<int> Review_Project_Name_ID { get; set; }
        public string SOSC_CSR_ID { get; set; }
        public Nullable<bool> Is_Return_Visit { get; set; }
        public string Remarks { get; set; }
    }
}
