//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhoneBook
    {
        public int PhoneBook_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Phone_Number { get; set; }
        public string Phone_Name { get; set; }
        public string patient_relation { get; set; }
    
        public virtual tbPatient tbPatient { get; set; }
        public virtual tbPhoneBook tbPhoneBook1 { get; set; }
        public virtual tbPhoneBook tbPhoneBook2 { get; set; }
    }
}
