//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReference_Information
    {
        public int Reference_Information_ID { get; set; }
        public string Information_Content { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<int> Sequence_Number { get; set; }
    
        public virtual tbReference_Information tbReference_Information1 { get; set; }
        public virtual tbReference_Information tbReference_Information2 { get; set; }
    }
}
