//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStaffDuty
    {
        public tbStaffDuty()
        {
            this.tbStaff = new HashSet<tbStaff>();
        }
    
        public int StaffDuty_ID { get; set; }
        public string StaffDuty_Name { get; set; }
    
        public virtual ICollection<tbStaff> tbStaff { get; set; }
    }
}
