//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRevisitSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVoice_Key
    {
        public int Voice_Key_ID { get; set; }
        public Nullable<int> Voice_Plan_ID { get; set; }
        public Nullable<int> Caller_Title_ID { get; set; }
        public Nullable<int> Investigation_Question_ID { get; set; }
        public string Answer_Marked_No { get; set; }
        public Nullable<System.DateTime> Record_Generate_Time { get; set; }
        public Nullable<bool> Is_Manual_Revisit { get; set; }
    
        public virtual tbCaller_Title tbCaller_Title { get; set; }
        public virtual tbInvestigation_Question tbInvestigation_Question { get; set; }
        public virtual tbVoice_Key tbVoice_Key1 { get; set; }
        public virtual tbVoice_Key tbVoice_Key2 { get; set; }
        public virtual tbVoice_Plan tbVoice_Plan { get; set; }
    }
}
